#
# Copyright (c) 2019, Digital Asset (Switzerland) GmbH and/or its affiliates. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
#

ARG sdk_vsn=1.5.0

FROM digitalasset/daml-sdk:${sdk_vsn}

WORKDIR /home/daml
COPY daml.yaml .
COPY daml ./daml

USER root
RUN chown -R daml daml.yaml
RUN chown daml -R daml/
USER daml

EXPOSE 6865

CMD ~/.daml/bin/daml start \
  --sandbox-option="--address=0.0.0.0" \
  --sandbox-port 6865 \
  --json-api-port=none \
  --start-navigator=false
