#
# Copyright (c) 2019, Digital Asset (Switzerland) GmbH and/or its affiliates. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
#

ARG sdk_vsn=1.4.0

FROM digitalasset/daml-sdk:${sdk_vsn}

WORKDIR /home/daml

COPY .daml/dist/StructuredTradeFinance.dar /home/daml/

USER root
RUN chown daml StructuredTradeFinance.dar
USER daml

EXPOSE 6865

CMD ~/.daml/bin/daml sandbox -- --address 0.0.0.0 --port 6865 --scenario DA.RefApps.StructuredTradeFinance.Main:setup StructuredTradeFinance.dar
